# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(858, 717)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(45, -1, -1, -1)
        self.horizontalLayout_2.setSpacing(50)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.checkBox_goo = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_goo.setFont(font)
        self.checkBox_goo.setChecked(True)
        self.checkBox_goo.setObjectName("checkBox_goo")
        self.horizontalLayout_2.addWidget(self.checkBox_goo)
        self.checkBox_bai = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_bai.setFont(font)
        self.checkBox_bai.setChecked(True)
        self.checkBox_bai.setObjectName("checkBox_bai")
        self.horizontalLayout_2.addWidget(self.checkBox_bai)
        self.checkBox_bing = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_bing.setFont(font)
        self.checkBox_bing.setChecked(True)
        self.checkBox_bing.setObjectName("checkBox_bing")
        self.horizontalLayout_2.addWidget(self.checkBox_bing)
        self.checkBox_jin = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_jin.setFont(font)
        self.checkBox_jin.setChecked(True)
        self.checkBox_jin.setObjectName("checkBox_jin")
        self.horizontalLayout_2.addWidget(self.checkBox_jin)
        self.checkBox_you = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_you.setFont(font)
        self.checkBox_you.setChecked(True)
        self.checkBox_you.setObjectName("checkBox_you")
        self.horizontalLayout_2.addWidget(self.checkBox_you)
        self.checkBox_zhi = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_zhi.setFont(font)
        self.checkBox_zhi.setChecked(True)
        self.checkBox_zhi.setObjectName("checkBox_zhi")
        self.horizontalLayout_2.addWidget(self.checkBox_zhi)
        self.gridLayout_5.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 75))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setContentsMargins(-1, 6, -1, 6)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setMaximumSize(QtCore.QSize(47, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout.addWidget(self.comboBox)
        self.textEdit_in = QtWidgets.QTextEdit(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textEdit_in.setFont(font)
        self.textEdit_in.setObjectName("textEdit_in")
        self.horizontalLayout.addWidget(self.textEdit_in)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 15)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.button_trans = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.button_trans.setFont(font)
        self.button_trans.setObjectName("button_trans")
        self.verticalLayout.addWidget(self.button_trans)
        self.button_clear = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.button_clear.setFont(font)
        self.button_clear.setObjectName("button_clear")
        self.verticalLayout.addWidget(self.button_clear)
        self.gridLayout.addLayout(self.verticalLayout, 0, 1, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_11.setContentsMargins(-1, 0, -1, 0)
        self.gridLayout_11.setHorizontalSpacing(6)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setHorizontalSpacing(6)
        self.gridLayout_10.setVerticalSpacing(0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.widget_goo = QtWidgets.QWidget(self.groupBox_2)
        self.widget_goo.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget_goo.setObjectName("widget_goo")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_goo)
        self.gridLayout_2.setContentsMargins(-1, 6, -1, 6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_goo = QtWidgets.QHBoxLayout()
        self.horizontalLayout_goo.setObjectName("horizontalLayout_goo")
        self.label = QtWidgets.QLabel(self.widget_goo)
        self.label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_goo.addWidget(self.label)
        self.textEdit_goo = QtWidgets.QTextEdit(self.widget_goo)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textEdit_goo.setFont(font)
        self.textEdit_goo.setObjectName("textEdit_goo")
        self.horizontalLayout_goo.addWidget(self.textEdit_goo)
        self.button_goo = QtWidgets.QPushButton(self.widget_goo)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.button_goo.setFont(font)
        self.button_goo.setObjectName("button_goo")
        self.horizontalLayout_goo.addWidget(self.button_goo)
        self.gridLayout_2.addLayout(self.horizontalLayout_goo, 0, 0, 1, 1)
        self.gridLayout_10.addWidget(self.widget_goo, 0, 0, 1, 1)
        self.widget_bai = QtWidgets.QWidget(self.groupBox_2)
        self.widget_bai.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget_bai.setObjectName("widget_bai")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_bai)
        self.gridLayout_3.setContentsMargins(-1, 6, -1, 6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_bai = QtWidgets.QHBoxLayout()
        self.horizontalLayout_bai.setObjectName("horizontalLayout_bai")
        self.label_2 = QtWidgets.QLabel(self.widget_bai)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_bai.addWidget(self.label_2)
        self.textEdit_bai = QtWidgets.QTextEdit(self.widget_bai)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textEdit_bai.setFont(font)
        self.textEdit_bai.setObjectName("textEdit_bai")
        self.horizontalLayout_bai.addWidget(self.textEdit_bai)
        self.button_bai = QtWidgets.QPushButton(self.widget_bai)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.button_bai.setFont(font)
        self.button_bai.setObjectName("button_bai")
        self.horizontalLayout_bai.addWidget(self.button_bai)
        self.gridLayout_3.addLayout(self.horizontalLayout_bai, 0, 0, 1, 1)
        self.gridLayout_10.addWidget(self.widget_bai, 1, 0, 1, 1)
        self.widget_bing = QtWidgets.QWidget(self.groupBox_2)
        self.widget_bing.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget_bing.setObjectName("widget_bing")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.widget_bing)
        self.gridLayout_6.setContentsMargins(-1, 6, -1, 6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.horizontalLayout_bing = QtWidgets.QHBoxLayout()
        self.horizontalLayout_bing.setObjectName("horizontalLayout_bing")
        self.label_3 = QtWidgets.QLabel(self.widget_bing)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_bing.addWidget(self.label_3)
        self.textEdit_bing = QtWidgets.QTextEdit(self.widget_bing)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textEdit_bing.setFont(font)
        self.textEdit_bing.setObjectName("textEdit_bing")
        self.horizontalLayout_bing.addWidget(self.textEdit_bing)
        self.button_bing = QtWidgets.QPushButton(self.widget_bing)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.button_bing.setFont(font)
        self.button_bing.setObjectName("button_bing")
        self.horizontalLayout_bing.addWidget(self.button_bing)
        self.gridLayout_6.addLayout(self.horizontalLayout_bing, 0, 0, 1, 1)
        self.gridLayout_10.addWidget(self.widget_bing, 2, 0, 1, 1)
        self.widget_jin = QtWidgets.QWidget(self.groupBox_2)
        self.widget_jin.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget_jin.setObjectName("widget_jin")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.widget_jin)
        self.gridLayout_7.setContentsMargins(-1, 6, -1, 6)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.horizontalLayout_jin = QtWidgets.QHBoxLayout()
        self.horizontalLayout_jin.setObjectName("horizontalLayout_jin")
        self.label_4 = QtWidgets.QLabel(self.widget_jin)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_jin.addWidget(self.label_4)
        self.textEdit_jin = QtWidgets.QTextEdit(self.widget_jin)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textEdit_jin.setFont(font)
        self.textEdit_jin.setObjectName("textEdit_jin")
        self.horizontalLayout_jin.addWidget(self.textEdit_jin)
        self.button_jin = QtWidgets.QPushButton(self.widget_jin)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.button_jin.setFont(font)
        self.button_jin.setObjectName("button_jin")
        self.horizontalLayout_jin.addWidget(self.button_jin)
        self.gridLayout_7.addLayout(self.horizontalLayout_jin, 0, 0, 1, 1)
        self.gridLayout_10.addWidget(self.widget_jin, 3, 0, 1, 1)
        self.widget_you = QtWidgets.QWidget(self.groupBox_2)
        self.widget_you.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget_you.setObjectName("widget_you")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.widget_you)
        self.gridLayout_8.setContentsMargins(-1, 6, -1, 6)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.horizontalLayout_you = QtWidgets.QHBoxLayout()
        self.horizontalLayout_you.setObjectName("horizontalLayout_you")
        self.label_5 = QtWidgets.QLabel(self.widget_you)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_you.addWidget(self.label_5)
        self.textEdit_you = QtWidgets.QTextEdit(self.widget_you)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textEdit_you.setFont(font)
        self.textEdit_you.setObjectName("textEdit_you")
        self.horizontalLayout_you.addWidget(self.textEdit_you)
        self.button_you = QtWidgets.QPushButton(self.widget_you)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.button_you.setFont(font)
        self.button_you.setObjectName("button_you")
        self.horizontalLayout_you.addWidget(self.button_you)
        self.gridLayout_8.addLayout(self.horizontalLayout_you, 0, 0, 1, 1)
        self.gridLayout_10.addWidget(self.widget_you, 4, 0, 1, 1)
        self.widget_zhi = QtWidgets.QWidget(self.groupBox_2)
        self.widget_zhi.setObjectName("widget_zhi")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.widget_zhi)
        self.gridLayout_9.setContentsMargins(-1, 6, -1, 6)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.horizontalLayout_zhi = QtWidgets.QHBoxLayout()
        self.horizontalLayout_zhi.setObjectName("horizontalLayout_zhi")
        self.label_6 = QtWidgets.QLabel(self.widget_zhi)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_zhi.addWidget(self.label_6)
        self.textEdit_zhi = QtWidgets.QTextEdit(self.widget_zhi)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textEdit_zhi.setFont(font)
        self.textEdit_zhi.setObjectName("textEdit_zhi")
        self.horizontalLayout_zhi.addWidget(self.textEdit_zhi)
        self.button_zhi = QtWidgets.QPushButton(self.widget_zhi)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.button_zhi.setFont(font)
        self.button_zhi.setObjectName("button_zhi")
        self.horizontalLayout_zhi.addWidget(self.button_zhi)
        self.gridLayout_9.addLayout(self.horizontalLayout_zhi, 0, 0, 1, 1)
        self.gridLayout_10.addWidget(self.widget_zhi, 5, 0, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_10, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 858, 17))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.checkBox_goo.setText(_translate("MainWindow", "谷歌"))
        self.checkBox_bai.setText(_translate("MainWindow", "百度"))
        self.checkBox_bing.setText(_translate("MainWindow", "必应"))
        self.checkBox_jin.setText(_translate("MainWindow", "金山"))
        self.checkBox_you.setText(_translate("MainWindow", "有道"))
        self.checkBox_zhi.setText(_translate("MainWindow", "知网"))
        self.groupBox.setTitle(_translate("MainWindow", "输入"))
        self.comboBox.setItemText(0, _translate("MainWindow", "自动"))
        self.comboBox.setItemText(1, _translate("MainWindow", "中->英"))
        self.comboBox.setItemText(2, _translate("MainWindow", "英->中"))
        self.button_trans.setText(_translate("MainWindow", "翻译"))
        self.button_clear.setText(_translate("MainWindow", "清空"))
        self.groupBox_2.setTitle(_translate("MainWindow", "结果"))
        self.label.setText(_translate("MainWindow", "谷歌"))
        self.button_goo.setText(_translate("MainWindow", "复制"))
        self.label_2.setText(_translate("MainWindow", "百度"))
        self.button_bai.setText(_translate("MainWindow", "复制"))
        self.label_3.setText(_translate("MainWindow", "必应"))
        self.button_bing.setText(_translate("MainWindow", "复制"))
        self.label_4.setText(_translate("MainWindow", "金山"))
        self.button_jin.setText(_translate("MainWindow", "复制"))
        self.label_5.setText(_translate("MainWindow", "有道"))
        self.button_you.setText(_translate("MainWindow", "复制"))
        self.label_6.setText(_translate("MainWindow", "知网"))
        self.button_zhi.setText(_translate("MainWindow", "复制"))

