# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 571)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 75))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout.addWidget(self.comboBox)
        self.textEdit_in = QtWidgets.QTextEdit(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textEdit_in.setFont(font)
        self.textEdit_in.setObjectName("textEdit_in")
        self.horizontalLayout.addWidget(self.textEdit_in)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 15)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.button_trans = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.button_trans.setFont(font)
        self.button_trans.setObjectName("button_trans")
        self.verticalLayout.addWidget(self.button_trans)
        self.button_clear = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.button_clear.setFont(font)
        self.button_clear.setObjectName("button_clear")
        self.verticalLayout.addWidget(self.button_clear)
        self.gridLayout.addLayout(self.verticalLayout, 0, 1, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.textEdit_goo = QtWidgets.QTextEdit(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textEdit_goo.setFont(font)
        self.textEdit_goo.setObjectName("textEdit_goo")
        self.gridLayout_2.addWidget(self.textEdit_goo, 0, 1, 1, 1)
        self.button_goo = QtWidgets.QPushButton(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.button_goo.setFont(font)
        self.button_goo.setObjectName("button_goo")
        self.gridLayout_2.addWidget(self.button_goo, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.textEdit_bai = QtWidgets.QTextEdit(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textEdit_bai.setFont(font)
        self.textEdit_bai.setObjectName("textEdit_bai")
        self.gridLayout_2.addWidget(self.textEdit_bai, 1, 1, 1, 1)
        self.button_bai = QtWidgets.QPushButton(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.button_bai.setFont(font)
        self.button_bai.setObjectName("button_bai")
        self.gridLayout_2.addWidget(self.button_bai, 1, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.textEdit_bing = QtWidgets.QTextEdit(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textEdit_bing.setFont(font)
        self.textEdit_bing.setObjectName("textEdit_bing")
        self.gridLayout_2.addWidget(self.textEdit_bing, 2, 1, 1, 1)
        self.button_bing = QtWidgets.QPushButton(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.button_bing.setFont(font)
        self.button_bing.setObjectName("button_bing")
        self.gridLayout_2.addWidget(self.button_bing, 2, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 3, 0, 1, 1)
        self.textEdit_jin = QtWidgets.QTextEdit(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textEdit_jin.setFont(font)
        self.textEdit_jin.setObjectName("textEdit_jin")
        self.gridLayout_2.addWidget(self.textEdit_jin, 3, 1, 1, 1)
        self.button_jin = QtWidgets.QPushButton(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.button_jin.setFont(font)
        self.button_jin.setObjectName("button_jin")
        self.gridLayout_2.addWidget(self.button_jin, 3, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 4, 0, 1, 1)
        self.textEdit_you = QtWidgets.QTextEdit(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textEdit_you.setFont(font)
        self.textEdit_you.setObjectName("textEdit_you")
        self.gridLayout_2.addWidget(self.textEdit_you, 4, 1, 1, 1)
        self.button_you = QtWidgets.QPushButton(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.button_you.setFont(font)
        self.button_you.setObjectName("button_you")
        self.gridLayout_2.addWidget(self.button_you, 4, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 5, 0, 1, 1)
        self.textEdit_zhi = QtWidgets.QTextEdit(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textEdit_zhi.setFont(font)
        self.textEdit_zhi.setObjectName("textEdit_zhi")
        self.gridLayout_2.addWidget(self.textEdit_zhi, 5, 1, 1, 1)
        self.button_zhi = QtWidgets.QPushButton(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.button_zhi.setFont(font)
        self.button_zhi.setObjectName("button_zhi")
        self.gridLayout_2.addWidget(self.button_zhi, 5, 2, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 2)
        self.gridLayout_2.setColumnStretch(1, 25)
        self.gridLayout_2.setColumnStretch(2, 2)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 17))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "输入"))
        self.comboBox.setItemText(0, _translate("MainWindow", "自动"))
        self.comboBox.setItemText(1, _translate("MainWindow", "中->英"))
        self.comboBox.setItemText(2, _translate("MainWindow", "英->中"))
        self.button_trans.setText(_translate("MainWindow", "翻译"))
        self.button_clear.setText(_translate("MainWindow", "清空"))
        self.groupBox_2.setTitle(_translate("MainWindow", "结果"))
        self.label.setText(_translate("MainWindow", "谷歌"))
        self.button_goo.setText(_translate("MainWindow", "复制"))
        self.label_2.setText(_translate("MainWindow", "百度"))
        self.button_bai.setText(_translate("MainWindow", "复制"))
        self.label_3.setText(_translate("MainWindow", "必应"))
        self.button_bing.setText(_translate("MainWindow", "复制"))
        self.label_4.setText(_translate("MainWindow", "金山"))
        self.button_jin.setText(_translate("MainWindow", "复制"))
        self.label_5.setText(_translate("MainWindow", "有道"))
        self.button_you.setText(_translate("MainWindow", "复制"))
        self.label_6.setText(_translate("MainWindow", "知网"))
        self.button_zhi.setText(_translate("MainWindow", "复制"))

